[graph]
all-features = true

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
confidence-threshold = 0.93

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
