[package]
name = "fetchloom-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fetchloom-engine = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true }
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Storage_FileSystem",
  "Win32_Storage_InstallableFileSystems",
  "Win32_System_Ioctl",
  "Win32_System_IO",
  "Win32_System_JobObjects",
  "Win32_System_Registry",
  "Win32_System_SystemInformation",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
