//! The third-party notice a binary ships beside, generated from the graph
//! rather than maintained by hand.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

const NOTICE: &str = "THIRD-PARTY-NOTICES.md";

const OWN_PREFIX: &str = "fetchloom-";

struct Package {
    name: String,
    version: String,
    license: String,
    repository: Option<String>,
    directory: PathBuf,
}

pub fn run(workspace: &Path, arguments: &[String]) -> ExitCode {
    let check = arguments.iter().any(|one| one == "--check");
    let packages = match read_graph(workspace) {
        Ok(packages) => packages,
        Err(reason) => {
            eprintln!("the dependency graph could not be read: {reason}");
            return ExitCode::from(1);
        }
    };
    let rendered = render(&packages);
    let path = workspace.join(NOTICE);
    if check {
        let held = std::fs::read_to_string(&path).unwrap_or_default();
        if held.replace("\r\n", "\n") == rendered {
            println!("{NOTICE} matches the graph, {} crates", packages.len());
            return ExitCode::SUCCESS;
        }
        eprintln!("run cargo xtask notices, because {NOTICE} does not match the graph");
        return ExitCode::from(1);
    }
    if let Err(reason) = std::fs::write(&path, &rendered) {
        eprintln!("{NOTICE} could not be written: {reason}");
        return ExitCode::from(1);
    }
    println!("{NOTICE} written, {} crates", packages.len());
    ExitCode::SUCCESS
}

fn read_graph(workspace: &Path) -> Result<Vec<Package>, String> {
    let output = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned()))
        .current_dir(workspace)
        .args(["metadata", "--format-version", "1", "--all-features"])
        .output()
        .map_err(|reason| reason.to_string())?;
    if !output.status.success() {
        return Err(String::from_utf8_lossy(&output.stderr).into_owned());
    }
    let text = String::from_utf8_lossy(&output.stdout).into_owned();
    let document: serde_json::Value =
        serde_json::from_str(&text).map_err(|reason| reason.to_string())?;
    let listed = document
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "cargo metadata named no packages".to_owned())?;

    let mut found = Vec::new();
    for one in listed {
        let name = string_at(one, "name");
        if name.starts_with(OWN_PREFIX) || name == "xtask" {
            continue;
        }
        let manifest = PathBuf::from(string_at(one, "manifest_path"));
        let directory = manifest.parent().unwrap_or(&manifest).to_path_buf();
        found.push(Package {
            name,
            version: string_at(one, "version"),
            license: one
                .get("license")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("stated in the crate rather than in its manifest")
                .to_owned(),
            repository: one
                .get("repository")
                .and_then(serde_json::Value::as_str)
                .map(str::to_owned),
            directory,
        });
    }
    found.sort_by(|left, right| {
        left.name
            .cmp(&right.name)
            .then_with(|| left.version.cmp(&right.version))
    });
    found.dedup_by(|left, right| left.name == right.name && left.version == right.version);
    Ok(found)
}

fn string_at(value: &serde_json::Value, key: &str) -> String {
    value
        .get(key)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default()
        .to_owned()
}

fn license_texts(directory: &Path) -> Vec<(String, String)> {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return Vec::new();
    };
    let mut found = Vec::new();
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let upper = name.to_uppercase();
        if !upper.starts_with("LICENSE") && !upper.starts_with("LICENCE") && upper != "COPYING" {
            continue;
        }
        if std::path::Path::new(&upper)
            .extension()
            .is_some_and(|end| end.eq_ignore_ascii_case("spdx"))
        {
            continue;
        }
        if let Ok(text) = std::fs::read_to_string(entry.path()) {
            found.push((name, text.replace("\r\n", "\n")));
        }
    }
    found.sort_by(|left, right| left.0.cmp(&right.0));
    found
}

fn render(packages: &[Package]) -> String {
    let mut out = String::new();
    out.push_str("# third-party notices\n\n");
    out.push_str(
        "fetchloom links the crates listed here. every one is reproduced with the license it states and, where the crate ships one, the text of that license. this file is generated by `cargo xtask notices` from `cargo metadata`, and `cargo xtask verify` fails when it does not match the graph.\n\n",
    );

    let mut by_license: BTreeMap<&str, Vec<&Package>> = BTreeMap::new();
    for package in packages {
        by_license
            .entry(package.license.as_str())
            .or_default()
            .push(package);
    }
    out.push_str("## what each license asks for\n\n");
    out.push_str("| license | crates | obligation this file discharges |\n|---|---|---|\n");
    for (license, held) in &by_license {
        let _ = writeln!(
            out,
            "| {license} | {} | {} |",
            held.len(),
            obligation(license)
        );
    }

    out.push_str("\n## crates\n\n");
    out.push_str("| crate | version | license | source |\n|---|---|---|---|\n");
    for package in packages {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            package.name,
            package.version,
            package.license,
            package.repository.as_deref().unwrap_or("not stated")
        );
    }

    out.push_str("\n## license texts\n\n");
    for package in packages {
        let texts = license_texts(&package.directory);
        if texts.is_empty() {
            continue;
        }
        let _ = writeln!(out, "### {} {}\n", package.name, package.version);
        for (name, text) in texts {
            let _ = write!(out, "`{name}`\n\n```\n{}\n```\n\n", text.trim_end());
        }
    }
    out
}

fn obligation(license: &str) -> &'static str {
    if license.contains("Apache-2.0") {
        "the notice and the license text travel with the binary, and any NOTICE file is reproduced"
    } else if license.contains("BSD") || license.contains("MIT") || license.contains("ISC") {
        "the copyright line and the permission notice travel with the binary"
    } else if license.contains("bzip2") {
        "the copyright line, the conditions and the disclaimer travel with the binary"
    } else if license.contains("Unicode") {
        "the data files' notice and permission text travel with the binary"
    } else if license.contains("Zlib") {
        "the notice is kept and the source is not misrepresented as original"
    } else {
        "the license is placed in the public domain or asks for nothing, and is listed for completeness"
    }
}
